### ISSUE TITLE
running the demo with statically compiled code

### ISSUE THREAD

**Issue by hroash** [quarkslab/pastis#13]
I compiled your demo statically:
clang -static -Wall -g demo.c -o ./bin/demo.ttt

and when I trying to run it using pastis and trintondse, I get:
1. I get exception, that my platform doesn't exist:
![image](https://github.com/quarkslab/pastis/assets/106006905/31b671a5-cbe1-4ffa-a295-75ca3db7fce3)

I fixed it by adding it on tritondse/loaders/cle_loader.py :
![image](https://github.com/quarkslab/pastis/assets/106006905/03479193-3847-4e4f-be42-00b13ec9518e)
and this really solved it

2. but it still didn't worked since it doesn't get the coverage:
![image](https://github.com/quarkslab/pastis/assets/106006905/50a6f799-6787-41a8-9e78-00165c2866d3)

when I tried to run the command by hand:
with statically compiled code, it never print "Runs....." :
![image](https://github.com/quarkslab/pastis/assets/106006905/6b659476-e210-41b9-a21c-4d7a3f038ffa)

without statically compiled code, it prints "Runs.....":
![image](https://github.com/quarkslab/pastis/assets/106006905/c18c32de-0415-48ca-b7b8-0edc64270762)

from some unknown reason this script didn't arrive vm.run(start, stop) in the qdbi_trace.py

**Comment by cnheitman** [comment]
Hi!

I pushed the fix for your first issue here quarkslab/tritondse@6b396df495c31871b271716f28ac7c6f64e33a13.

Regarding the other issue, in order to use `pyqbdipreload` you need to dynamically compiled your target as it relies on `LD_PRELOAD` for injecting itself into the target process. So it won't work on a statically compile binary.

It should have worked on the other case, though. To be sure, you are using the `fsm-demo.c` target from the doc, rigth? In that case, the problem could be that it is expecting input from `stdin`. Try the following:

```console
$ python -mpyqbdipreload <redacted>/tritondse/qbdi_trace.py ./demo.ttt < ../initial/initial.seed
Run start
Current state: 00
Back to state: 00
Run finished: 0.02s
```

**Comment by hroash** [comment]
on the other case where the code was compiled dynamically it worked, I didn't had issue with it.

**Comment by cnheitman** [comment]
My bad, I misunderstood. So if everything is working as expected, I'll close this issue.

Thanks for reporting the bug on TritonDSE!
