### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by gy741** [quarkslab/pastis#3]
Hello,

The code has been removed from the repository.

So the file does not exist and an error occurs.

```
    ./contrib/setup-cadical.sh && \
    ./contrib/setup-btor2tools.sh && \
    ./contrib/setup-symfpu.sh && \
```

https://github.com/quarkslab/pastis/blob/6d25f36db5bc578d01dfe383dcf485168cad9110/Dockerfile#L50C1-L52C35

https://github.com/bitwuzla/bitwuzla/tree/main/contrib

**Comment by cnheitman** [comment]
Hi, commit [21f5e0b](https://github.com/quarkslab/pastis/commit/21f5e0b47c2039dabdc361cf392cb508e0b8be11) should fix this. Can you try again?

**Comment by gy741** [comment]
Hello, @cnheitman Thanks for the quick action.
It works fine.

I have one question for you.
I want to use afl with less dependencies due to closed network issues.
Can I use afl instead of afl++?
Without adding a fuzzer?

Ref : https://github.com/google/AFL

**Comment by cnheitman** [comment]
Hey, @gy741. You might be able to use AFL instead of AFL++ as the command-line is be very similar (same goes for the stats file), just try pointing `AFLPP_PATH` to your AFL installation. I haven't test it myself but in principle it should work. In case you get an error, you can try modifying/tweaking function [start](https://github.com/quarkslab/pastis/blob/21f5e0b47c2039dabdc361cf392cb508e0b8be11/engines/pastis-aflpp/pastisaflpp/aflpp.py#L49) in `aflpp.py`.
